### ISSUE TITLE
if "change password" is allowed for a group/role/user, it can change Super-Admins password too

### ISSUE THREAD

**Issue by michapixel** [aryehraber/statamic-impersonator#15]
That definitely shouldn't be allowed. 

Since Roles, besides Super Admins, are completely free to edit, and therefor can't be checked security-wise, this addon should at least block changing passwords/profile of Super-Admins.

**Comment by aryehraber** [comment]
Hmm yeah, I agree that there should be some level of security at the Super Admin level. Currently once you start an impersonation session, Statamic/Laravel thinks you are that user, so stopping specific features like password-resets is tricky. I think instead I'll stop Super Admins being able to impersonate each other.

I'm open to a PR if you need this ASAP, otherwise I'll try and find some time for this (might take a while). Thanks!

**Comment by michapixel** [comment]
I can wait ;)


Aryeh Raber ***@***.***> schrieb am Fr., 10. Sept. 2021,
17:43:

**Comment by aryehraber** [comment]
I believe this issue was fixed in a recent version, since non-Super Admins can no longer impersonate Super Admin users.

See PR https://github.com/aryehraber/statamic-impersonator/pull/16.
