### ISSUE TITLE
Impersonator utility screen unusable for high number of users

### ISSUE THREAD

**Issue by mikemartin** [aryehraber/statamic-impersonator#21]
Hey @aryehraber 

I'm wondering how you could improve the Impersonator utility screen interface for a high number of users. Currently it's a dropdown but obviously loading 15000+ users isn't going to work great.

Few ideas to replace the dropdown selector:

a) Simple text field. Most of the time I know the email address I want to impersonate, it would be easy enough to paste the email address.

b) Stack selector for selecting user. Not sure how difficult this is but it would be the ideal UI pattern as it includes pagination.

c) Auto-complete search and select.

<img width="1009" alt="Screen Shot 2021-12-23 at 2 41 16 pm" src="https://user-images.githubusercontent.com/414211/147185622-55d50de3-c399-403d-b9ab-d7b5e531698b.png">

**Comment by aryehraber** [comment]
Yeah fair point, I've never had _that_ many users on a Statamic site so it's never been an issue. 

I think option (a) could be a decent (simple) solution via a config option, so you as a dev can change the default "dropdown" to "text" field and then it'll work as you suggest. 

Having said that, the User Index view is probably the better way to manage Impersonations in that case.

I'm open to a PR if you're able to contribute, otherwise I'll have to see when I have time to dive into it. Thanks!
